### ISSUE TITLE
New version number is inconsistent

### ISSUE THREAD

**Issue by Y0hy0h** [dillonkearns/elm-pages#127]
There appears to be a hickup somewhere:

The badge in the README says the latest Elm version is `6.0.0`. When I run `elm install dillonkearns/elm-pages` it also installs `6.0.0`.

But the changelog lists `5.0.3` as the latest tag and the package documentation `5.0.2`, though by hacking the URL you can show the [page for `6.0.0`](https://package.elm-lang.org/packages/dillonkearns/elm-pages/6.0.0/), but it says that "`5.0.2` is the latest tag".

🤔

**Comment by dillonkearns** [comment]
Thanks for catching that Johannes! I fixed the changelog: https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-ELM.md#600---2020-07-14.

What happened is I updated the changelog, expecting it to be a patch bump. But of course it would have to be at least a minor version bump since there are some new functions for dimensions. Turns out it was actually a major bump because it changes the API of something used by the generated code. It's unfortunate to have that version change noise, I've thought about strategies for that before.

Since some of those internals are part of the public package, there might not be a way to prevent breaking changes when new things are added in the internals like that unfortunately. If you have any ideas, though, I'd love to hear them!

**Comment by Y0hy0h** [comment]
That explains it. :) I've suspected something like that.

The only thing that still doesn't work for me is the [latest documentation](https://package.elm-lang.org/packages/dillonkearns/elm-pages/latest/) still pointing to `5.0.2`.

**Comment by matheus23** [comment]
That might be a caching issue on your end @Y0hy0h. If I remember correctly, this has happened before. It is working for me right now :)

**Comment by Y0hy0h** [comment]
Yes, reloading the package website bypassing the cache does the trick. Interesting, how aggressive caching can be. :D
